language: python
python: "3.6"
  
install:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt

script:
  - python -m pytest --cov-report term --cov=tests/

after_success:
  - codecov
