name: PyMPDATA

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          pip install -e .
      - run: |
          python -c "import PyMPDATA"
      # note: this installs PyMPDATA-examples including its dependencies which inclde PyMPDATA itself...
      - run: |
          pip install -r requirements.txt
      # note: ... hence reverting to the currently tested version
      - run: |
          pip install -e .
      # TODO #184 (https://github.com/numba/numba/issues/6350#issuecomment-728174860)
      - if: matrix.platform == 'ubuntu-latest'
        env:
          NUMBA_THREADING_LAYER: omp
        run: pytest -p no:unraisableexception

      - if: matrix.platform != 'ubuntu-latest'
        run: pytest -p no:unraisableexception